services:
  - type: web
    name: bonita-super
    env: python
    buildCommand: |
      ls -la
      ls -la APP_DEFINITIVA_FINAL_PLUS || true
      pip install --upgrade pip
      pip install -r requirements.txt || pip install -r APP_DEFINITIVA_FINAL_PLUS/requirements.txt || pip install fastapi uvicorn[standard] sqlalchemy psycopg2-binary python-multipart pytz
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT || uvicorn APP_DEFINITIVA_FINAL_PLUS.main:app --host 0.0.0.0 --port $PORT
