services:
  - type: web
    name: bonita-super
    env: python
    rootDir: APP_DEFINITIVA_FINAL_PLUS/app
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    


